Description: >
  This template creates private hosted zone resouces in member accounts.
  It is meant to be deployed as a stack set in all org accounts and all regions where you need to
  create infrastructure that might be part of the hosted zone.

Parameters:
  NetworkAccountId:
    Type: String
    Default: 685976753954

  PrimaryRegion:
    Type: String
    Default: us-east-2

Resources:

  # Send EC2 instance create and terminate events to the default EventBridge bus in the network account,
  # that will trigger a Lambda to create/remove the DNS entry in the private hosted zone for the instance
  Ec2InstanceCreateEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: Ec2InstanceCreateEventBridgeRule
      Description: Responds to EC2 instance create events
      EventPattern:
        detail:
          eventSource:
            - ec2.amazonaws.com
          eventName:
            - RunInstances
            - TerminateInstances
      State: ENABLED
      Targets:
        -
          Id: NetworkAccountDefaultEventBridgeBus
          Arn: !Sub 'arn:aws:events:${PrimaryRegion}:${NetworkAccountId}:event-bus/default'
          # This role is created in 2-all-accounts-primary-region-stackset.yml.
          # Note that we can't export/import the ARN because the template that creates the role
          # might have been run in a different region. An alternative to hard-coding this ARN is
          # to save update the 2-all-accounts-primary-region-stackset.yml template to save the 
          # ARN of the role in an SSM parameter, then set up the get-ssm-param lambda as
          # a custom CloudFormation resource in this template to retrieve the role ARN from SSM.
          RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/Ec2InstanceCreateEventBridgeRuleRole'